name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm run build --production

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm start

      - name: Build backend
        run: |
          cd backend
          npm run build

  deploy-frontend:
    name: Deploy Frontend
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy frontend to server
        env:
          SERVER_HOST: ${{ secrets.FRONTEND_SERVER_HOST }}
          SERVER_USER: ${{ secrets.FRONTEND_SERVER_USER }}
          SERVER_KEY: ${{ secrets.FRONTEND_SERVER_KEY }}
        run: |
          ssh -i ${{ env.SERVER_KEY }} ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'bash -s' < ./frontend/deploy.sh

  deploy-backend:
    name: Deploy Backend
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy backend to server
        env:
          SERVER_HOST: ${{ secrets.BACKEND_SERVER_HOST }}
          SERVER_USER: ${{ secrets.BACKEND_SERVER_USER }}
          SERVER_KEY: ${{ secrets.BACKEND_SERVER_KEY }}
        run: |
          ssh -i ${{ env.SERVER_KEY }} ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'bash -s' < ./backend/deploy.sh
